FROM arm64v8/httpd:2.4

# Update UID/GID for web user to use (probably) same user as at build time
RUN usermod -u 1000 www-data && \
    groupmod -g 1000 www-data

# Copy in apache config
COPY docker-support/httpd.conf /usr/local/apache2/conf/httpd.conf
COPY docker-support/apache2-run docker-support/entrypoint /usr/local/bin/
COPY docker-support/.image-version /etc/image-version

ENTRYPOINT ["/usr/local/bin/entrypoint"]

CMD [ "/usr/local/bin/apache2-run" ]